version: '3.8'
networks:
  event:
services:
  nginx_event:
    image: nginx:alpine
    restart: always
    container_name: nginx_event
    ports:
      - '8044:8044'
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf:rw
    depends_on:
      - event
      - event_db
    networks:
      - event
      
  event_db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: 'dimas'
      POSTGRES_PASSWORD: 'dimasw1950'
      POSTGRES_DB: 'event'
    ports:
      - '5444:5432'
    networks:
      - event

  event:
    container_name: event
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    networks:
      - event
